// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP2vkwStMHycbKBO4PNol-b1pcFP46DHY',
    appId: '1:371055618192:web:4e06550bcad131a5555015',
    messagingSenderId: '371055618192',
    projectId: 'juconnects-31731',
    authDomain: 'juconnects-31731.firebaseapp.com',
    storageBucket: 'juconnects-31731.firebasestorage.app',
    measurementId: 'G-ERD7FT8WK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzmHQYJxXWkfw_GpMYnpAGGC0lNs3Vmtc',
    appId: '1:371055618192:android:636b32226fdc5cf2555015',
    messagingSenderId: '371055618192',
    projectId: 'juconnects-31731',
    storageBucket: 'juconnects-31731.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMTpv5lThExjJl22XcdZBjDYb7SgfhoJ0',
    appId: '1:371055618192:ios:d498ce0895e77225555015',
    messagingSenderId: '371055618192',
    projectId: 'juconnects-31731',
    storageBucket: 'juconnects-31731.firebasestorage.app',
    iosBundleId: 'com.example.juConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMTpv5lThExjJl22XcdZBjDYb7SgfhoJ0',
    appId: '1:371055618192:ios:d498ce0895e77225555015',
    messagingSenderId: '371055618192',
    projectId: 'juconnects-31731',
    storageBucket: 'juconnects-31731.firebasestorage.app',
    iosBundleId: 'com.example.juConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP2vkwStMHycbKBO4PNol-b1pcFP46DHY',
    appId: '1:371055618192:web:d8d0c81c7df1abde555015',
    messagingSenderId: '371055618192',
    projectId: 'juconnects-31731',
    authDomain: 'juconnects-31731.firebaseapp.com',
    storageBucket: 'juconnects-31731.firebasestorage.app',
    measurementId: 'G-4JJBFKT0XE',
  );
}
